-- ==============================================================================
-- ASC Drop In Tutor Admin Interface - Master Database Schema
-- ==============================================================================
-- Run this entire script to build or reset the database structure.
-- ==============================================================================

USE asc_dropin_tutoring;

-- 1. Drop existing tables in reverse order to avoid foreign key constraint errors
DROP TABLE IF EXISTS status;
DROP TABLE IF EXISTS tutor_course;
DROP TABLE IF EXISTS shift;
DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS tutors;
DROP TABLE IF EXISTS admins;

-- ==============================================================================
-- 2. Create Core Tables (No Foreign Keys)
-- ==============================================================================

-- ADMINS: Stores dashboard login credentials
CREATE TABLE admins (
    admin_id VARCHAR(50) PRIMARY KEY,
    first_name VARCHAR(50) NULL,
    last_name VARCHAR(50) NULL,
    email VARCHAR(255) NULL,
    pass VARCHAR(255) NOT NULL
);

-- TUTORS: Stores basic tutor information
CREATE TABLE tutors (
    student_id VARCHAR(50) PRIMARY KEY,
    first_name VARCHAR(50) NULL
);

-- COURSE: Stores the master list of available courses
CREATE TABLE course (
    course_code VARCHAR(15) PRIMARY KEY,
    course_title VARCHAR(100) NULL,
    course_subject VARCHAR(100) NULL
);

-- ==============================================================================
-- 3. Create Relational Tables (Contains Foreign Keys)
-- ==============================================================================

-- TUTOR_COURSE: Maps which tutors teach which courses
CREATE TABLE tutor_course (
    student_id VARCHAR(50),
    course_code VARCHAR(15),
    PRIMARY KEY (student_id, course_code),
    FOREIGN KEY (student_id) REFERENCES tutors(student_id) ON DELETE CASCADE,
    FOREIGN KEY (course_code) REFERENCES course(course_code) ON DELETE CASCADE
);

-- SHIFT: Stores the weekly template schedule
CREATE TABLE shift (
    shift_id VARCHAR(50) PRIMARY KEY,
    student_id VARCHAR(50),
    day_of_week VARCHAR(15) NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    FOREIGN KEY (student_id) REFERENCES tutors(student_id) ON DELETE CASCADE
);

-- STATUS: The dynamic daily schedule generated by the PHP script
-- (Tracks if a tutor is Upcoming, Active, Completed, or Cancelled on a specific date)
CREATE TABLE status (
    status_id VARCHAR(50) PRIMARY KEY,
    shift_id VARCHAR(50) NULL,
    `date` DATE NULL,
    status_state enum('Upcoming', 'Active', 'Late', 'Full', 'Cancelled') DEFAULT 'Upcoming',
    admin_id VARCHAR(50) NULL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);